### ISSUE TITLE
CorruptedTreeException: B+Tree is corrupted

### ISSUE THREAD

**Issue by meanother** [apache/ignite#10491]
Java version 1.8
Ignite version 2.14

The error appears at the stage of writing data to the table using the following construction
```
insert into saa_sv_rawdbo_dm_transactions_month
select ... from ...
```
Use without `template=onheapcache` work currently

```
CREATE TABLE saa_sv_rawdbo_dm_transactions_month(
 pay_client_pin VARCHAR
 , pay_transaction_count int
 , pay_tarif_plan_set VARCHAR
 ...
 , PRIMARY KEY (pay_client_pin)
) WITH "affinityKey=pay_client_pin,DATA_REGION=persist_data_region,template=onheapcache";
```

`CREATE INDEX idx_fin_client ON public.saa_sv_rawdbo_dm_transactions_month(pay_client_pin) INLINE_SIZE 6;`

```
<property name="dataRegionConfigurations">
 <list>
  <bean class="org.apache.ignite.configuration.DataRegionConfiguration">
   <property name="name" value="persist_data_region"/>
   <property name="initialSize" value="#{1L * 1024 * 1024 * 1024}"/>
   <property name="maxSize" value="#{100L * 1024 * 1024 * 1024}"/>
   <property name="pageEvictionMode" value="RANDOM_2_LRU"/>
   <!-- persist options -->
   <property name="persistenceEnabled" value="true"/>
   <property name="warmUpConfiguration">
    <bean class="org.apache.ignite.configuration.LoadAllWarmUpConfiguration"/>
   </property>
  </bean>
 </list>
</property>

<property name="cacheConfiguration">
<list>
 <bean abstract="true" class="org.apache.ignite.configuration.CacheConfiguration" id="cache-template-bean">
  <property name="name" value="onheapcache*"/>
  <property name="sqlOnheapCacheEnabled" value="true"/>
 </bean>
</list>
</property>
```

log:  
```
[12:38:31,424][SEVERE][build-idx-runner-#228][] Critical system error detected. Will be handled accordingly to configured handler [hnd=StopNodeOrHaltFailureHandler [tryStop=false, timeout=0, super=AbstractFailureHandler [ignoredFailureTypes=UnmodifiableSet [SYSTEM_WORKER_BLOCKED, SYSTEM_CRITICAL_OPERATION_TIMEOUT]]], failureCtx=FailureContext [type=CRITICAL_ERROR, err=class o.a.i.i.processors.cache.persistence.tree.CorruptedTreeException: B+Tree is corrupted [groupId=-288979615, pageIds=[844420635189922], cacheId=-288979615, cacheName=SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH, indexName=IDX_FIN_CLIENT, msg=Runtime failure on row: Row@5c1a42b0[ key: A201IX, val: SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH_177aaa96_e8b5_4ee1_baff_10353741c660 [idHash=1390257987, hash=-511005807, PAY_TRANSACTION_COUNT=2, ] ][ A201IX, A201IX ]]]]
class org.apache.ignite.internal.processors.cache.persistence.tree.CorruptedTreeException: B+Tree is corrupted [groupId=-288979615, pageIds=[844420635189922], cacheId=-288979615, cacheName=SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH, indexName=IDX_FIN_CLIENT, msg=Runtime failure on row: Row@5c1a42b0[ key: A201IX, val: SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH_177aaa96_e8b5_4ee1_baff_10353741c660 [idHash=1390257987, hash=-511005807, PAY_TRANSACTION_COUNT=2, PAY_TARIF_PLAN_SET=11] ][ A201IX, A201IX ]]

        at org.apache.ignite.internal.cache.query.index.sorted.inline.InlineIndexTree.corruptedTreeException(InlineIndexTree.java:561)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.doPut(BPlusTree.java:2671)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.put(BPlusTree.java:2602)
        at org.apache.ignite.internal.cache.query.index.sorted.inline.InlineIndexImpl.putx(InlineIndexImpl.java:348)
        at org.apache.ignite.internal.cache.query.index.sorted.inline.InlineIndexImpl.onUpdate(InlineIndexImpl.java:325)
        at org.apache.ignite.internal.cache.query.index.IndexProcessor.lambda$createIndexDynamically$0(IndexProcessor.java:225)
        at org.apache.ignite.internal.processors.query.schema.SchemaIndexCachePartitionWorker$SchemaIndexCacheVisitorClosureWrapper.apply(SchemaIndexCachePartitionWorker.java:302)
        at org.apache.ignite.internal.processors.cache.GridCacheMapEntry.updateIndex(GridCacheMapEntry.java:4193)
        at org.apache.ignite.internal.processors.query.schema.SchemaIndexCachePartitionWorker.processKey(SchemaIndexCachePartitionWorker.java:236)
        at org.apache.ignite.internal.processors.query.schema.SchemaIndexCachePartitionWorker.processPartition(SchemaIndexCachePartitionWorker.java:191)
        at org.apache.ignite.internal.processors.query.schema.SchemaIndexCachePartitionWorker.body(SchemaIndexCachePartitionWorker.java:130)
        at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: class org.apache.ignite.IgniteException: Failed to store new index row.
        at org.apache.ignite.internal.cache.query.index.sorted.inline.io.AbstractInlineInnerIO.storeByOffset(AbstractInlineInnerIO.java:106)
        at org.apache.ignite.internal.cache.query.index.sorted.inline.io.AbstractInlineInnerIO.storeByOffset(AbstractInlineInnerIO.java:37)
        at org.apache.ignite.internal.processors.cache.persistence.tree.io.BPlusIO.store(BPlusIO.java:228)
        at org.apache.ignite.internal.processors.cache.persistence.tree.io.BPlusIO.insert(BPlusIO.java:317)
        at org.apache.ignite.internal.processors.cache.persistence.tree.io.BPlusInnerIO.insert(BPlusInnerIO.java:150)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Put.insertSimple(BPlusTree.java:3962)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Put.insert(BPlusTree.java:3944)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Put.access$1700(BPlusTree.java:3786)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Insert.run0(BPlusTree.java:505)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Insert.run0(BPlusTree.java:486)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$GetPageHandler.run(BPlusTree.java:6216)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$GetPageHandler.run(BPlusTree.java:6202)
        at org.apache.ignite.internal.processors.cache.persistence.tree.util.PageHandler.writePage(PageHandler.java:381)
        at org.apache.ignite.internal.processors.cache.persistence.DataStructure.write(DataStructure.java:348)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.access$11500(BPlusTree.java:162)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Put.tryInsert(BPlusTree.java:4100)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree$Put.finishOrLockTail(BPlusTree.java:3824)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.putDown(BPlusTree.java:3035)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.putDown(BPlusTree.java:3022)
        at org.apache.ignite.internal.processors.cache.persistence.tree.BPlusTree.doPut(BPlusTree.java:2631)
        ... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.apache.ignite.internal.cache.query.index.sorted.QueryIndexRowHandler.indexKey(QueryIndexRowHandler.java:92)
        at org.apache.ignite.internal.cache.query.index.sorted.IndexRowImpl.key(IndexRowImpl.java:67)
        at org.apache.ignite.internal.cache.query.index.sorted.inline.io.AbstractInlineInnerIO.storeByOffset(AbstractInlineInnerIO.java:96)
        ... 32 more
[12:38:31,426][SEVERE][build-idx-runner-#228][FailureProcessor] A critical problem with persistence data structures was detected. Please make backup of persistence storage and WAL files for further analysis. Persistence storage path: null WAL path: db/wal WAL archive path: db/wal/archive
[12:38:31,426][SEVERE][build-idx-runner-#228][FailureProcessor] No deadlocked threads detected.
[12:38:31,841][SEVERE][build-idx-runner-#228][FailureProcessor] Thread dump at 2023/01/23 12:38:31 MSK
Thread [name="stat-mgmt-#234", id=307, state=TIMED_WAITING, blockCnt=0, waitCnt=1]
    Lock [object=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@7e9d4a5b, ownerName=null, ownerId=-1]
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

Thread [name="checkpoint-runner-IO-#233", id=306, state=WAITING, blockCnt=1, waitCnt=9912]
    Lock [object=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@22493384, ownerName=null, ownerId=-1]
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

Thread [name="checkpoint-runner-IO-#232", id=305, state=WAITING, blockCnt=3, waitCnt=9936]
    Lock [object=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@22493384, ownerName=null, ownerId=-1]
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

...


[12:38:31,998][SEVERE][build-idx-runner-#228][] JVM will be halted immediately due to the failure: [failureCtx=FailureContext [type=CRITICAL_ERROR, err=class o.a.i.i.processors.cache.persistence.tree.CorruptedTreeException: B+Tree is corrupted [groupId=-288979615, pageIds=[844420635189922], cacheId=-288979615, cacheName=SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH, indexName=IDX_FIN_CLIENT, msg=Runtime failure on row: Row@5c1a42b0[ key: A201IX, val: SQL_PUBLIC_SAA_SV_RAWDBO_DM_TRANSACTIONS_MONTH_177aaa96_e8b5_4ee1_baff_10353741c660 [idHash=1390257987, hash=-511005807, PAY_TRANSACTION_COUNT=2, PAY_TARIF_PLAN_SET=11] ][ A201IX, A201IX ]]]]

```

**Comment by ivandasch** [comment]
@meanother Do I understand correctly, that you have tried to create an additional index on the key field and this action led to a failure?

**Comment by meanother** [comment]
1) Create table `X`, fill it with data (or they are already there)
2) Create table saa_sv_rawdbo_dm_transactions_month, create index idx_fin_client (both entities are empty)

3) We fill the table saa_sv_rawdbo_dm_transactions_month with data - via
```
insert into saa_sv_rawdbo_dm_transactions_month
select ... from X where condition
```
4) we fall with an error

**Comment by alex-plekhanov** [comment]
JIra ticket created: https://issues.apache.org/jira/browse/IGNITE-19495

**Comment by ivandasch** [comment]
[IGNITE-19495](https://issues.apache.org/jira/browse/IGNITE-19495) Fixed here
