### ISSUE TITLE
Ignite 2.14.0, .NET, failed to create page directory, JDK 17

### ISSUE THREAD

**Issue by wasabii** [apache/ignite#10598]
Using 2.14.0, getting the given exception when calling Ignition.Start against OpenJDK 17:

```
JavaException: class org.apache.ignite.IgniteException: Failed to start processor: GridProcessorAdapter []
	at org.apache.ignite.internal.util.IgniteUtils.convertException(IgniteUtils.java:1145)
	at org.apache.ignite.internal.processors.platform.PlatformAbstractBootstrap.start(PlatformAbstractBootstrap.java:48)
	at org.apache.ignite.internal.processors.platform.PlatformIgnition.start(PlatformIgnition.java:74)
Caused by: class org.apache.ignite.IgniteCheckedException: Failed to start processor: GridProcessorAdapter []
	at org.apache.ignite.internal.IgniteKernal.startProcessor(IgniteKernal.java:1787)
	at org.apache.ignite.internal.IgniteKernal.start(IgniteKernal.java:1066)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:1757)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1679)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1121)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:631)
	at org.apache.ignite.internal.processors.platform.PlatformAbstractBootstrap.start(PlatformAbstractBootstrap.java:43)
	... 1 more
Caused by: class org.apache.ignite.IgniteCheckedException: Failed to create page store work directory: C:\ignitework\db\0_0_0_0_0_0_0_1_127_0_0_1_172_20_240_1_172_20_48_1_172_23_224_1_172_23_48_1_192_168_175_81_2603_8080_7400_45d9_2c57_895a_1fc0_9b07_2603_8080_7400_45d9_350c_88b1_7dc7_29f8_2603_8080_7400_45d9_6ee0_c850_1080_e364_2603_8080_7400_45d9_7ddf_2fff_94ce_4d0f_2603_8080_7400_45d9_7dee_c31b_fa5c_4897_2603_8080_7400_45d9_9d14_a51d_7729_c0c9_2603_8080_7400_45d9_d96_17d8_4e99_1e77_2603_8080_7400_45d9_f88f_c2b5_7a72_f08b_44120
	at org.apache.ignite.internal.util.IgniteUtils.ensureDirectory(IgniteUtils.java:9971)
	at org.apache.ignite.internal.processors.cache.GridLocalConfigManager.<init>(GridLocalConfigManager.java:127)
	at org.apache.ignite.internal.processors.cache.GridCacheProcessor.start(GridCacheProcessor.java:618)
	at org.apache.ignite.internal.IgniteKernal.startProcessor(IgniteKernal.java:1784)
	... 7 more

```

I had added custom JvmOptions consisting of all of the various options I found in jvmdefaults.sh. This advanced it a bit.

This directory name is kind of insane. What's it trying to do? And why?

**Comment by wasabii** [comment]
I did try to move the work directory to a number of different locations. Shorten the path. Etc. No luck.

**Comment by ptupitsyn** [comment]
Do you happen to have a lot of network interfaces? That long part of the path comes from Consistent Id, which is a concatenation of addresses (IPs) from all network interfaces on the machine.

A workaround is to set ConsistentId manually - just make sure it is different across nodes:

```csharp
var cfg = new IgniteConfiguration
{
    ConsistentId = "node-1"
};

var ignite = Ignition.Start(cfg);
```

**Comment by wasabii** [comment]
Oh. Yeah. Standard Windows machine these days. Running HyperV. IPv6 enabled by default.

**Comment by wasabii** [comment]
Yup. That solved it.

**Comment by wasabii** [comment]
I don't really think using IP addresses is a safe consistent ID, actually. These things come and go.

**Comment by wasabii** [comment]
Kubernetes.

**Comment by ggjtm** [comment]
Another workaround for Kubernetes (or anything else) would be to pass the value of the UUID of the persistent storage volume used by the ignite node to the Ignite instance as `IGNITE_OVERRIDE_CONSISTENT_ID` environment variable.

I think using all the node's enumerated IPv6 addresses is wrong (bug) because many OS implementations use [RFC8981](https://datatracker.ietf.org/doc/html/rfc8981) temporary addresses that recycle very frequently in order to prevent leaking permanent IP addresses.
