### ISSUE TITLE
failed to handle request: CACHE_METRICS

### ISSUE THREAD

**Issue by 1ssqq1lxr** [apache/ignite#10926]
ignite version:2.14.0,If allowed for a long time, this exception will be thrown, but the cluster function is OK
exception:
2023-09-09 06:30:41.244 ERROR [rest-#13104][:] - Failed to handle request: CACHE_METRICS
org.apache.ignite.IgniteCheckedException: Failed to find cache for given cache name: default
	at org.apache.ignite.internal.processors.rest.handlers.cache.GridCacheCommandHandler.cache(GridCacheCommandHandler.java:353) ~[fluxmq-starter.jar:?]
	at org.apache.ignite.internal.processors.rest.handlers.cache.GridCacheCommandHandler.localCache(GridCacheCommandHandler.java:828) ~[fluxmq-starter.jar:?]
	at org.apache.ignite.internal.processors.rest.handlers.cache.GridCacheCommandHandler.executeCommand(GridCacheCommandHandler.java:792) ~[fluxmq-starter.jar:?]
	at org.apache.ignite.internal.processors.rest.handlers.cache.GridCacheCommandHandler.handleAsync(GridCacheCommandHandler.java:652) ~[fluxmq-starter.jar:?]
	at org.apache.ignite.internal.processors.rest.GridRestProcessor.handleRequest0(GridRestProcessor.java:326) ~[fluxmq-starter.jar:?]
	at org.apache.ignite.internal.processors.rest.GridRestProcessor.handleRequest(GridRestProcessor.java:312) ~[fluxmq-starter.jar:

**Comment by sk0x50** [comment]
Hello @1ssqq1lxr ,

I have only one idea - the required cache, `default` was destroyed and no longer available. Could you please check that this cache really exists in the cluster?
