### ISSUE TITLE
"Failed to write class name to file" error occurring when running .Net server and multiple clients

### ISSUE THREAD

**Issue by JamesPDev** [apache/ignite#11025]
We run Apache Ignite from several .Net 6 applications and have recently upgrade from version 2.11 to 2.15. Post the upgrade we’ve noticed we regularly get the following error in our logs:

```
[2023-10-30 09:58:17.859 +00:00 ERR 16] Failed to write class name to file [platformId=1, id=-480146029, clsName=System.Collections.Generic.List`1[[<OneOfMyDomainModels>]], file=D:\Software\Ignite\apache-ignite-slim-2.15.0-bin\work\db\marshaller\-480146029.classname1] { nativeErrorInfo: "java.nio.file.AccessDeniedException: D:\Software\Ignite\apache-ignite-slim-2.15.0-bin\work\db\marshaller\-480146029.classname1-621646209.tmp -> D:\Software\Ignite\apache-ignite-slim-2.15.0-bin\work\db\marshaller\-480146029.classname1
               at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
               at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
               at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
               at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
               at java.nio.file.Files.move(Files.java:1395)
               at org.apache.ignite.internal.MarshallerMappingFileStore.writeMapping(MarshallerMappingFileStore.java:103)
               at org.apache.ignite.internal.MappingStoreTask.run(MappingStoreTask.java:57)
               at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:7487)
               at org.apache.ignite.internal.processors.closure.GridClosureProcessor$1.body(GridClosureProcessor.java:649)
               at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:125)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
               at java.lang.Thread.run(Thread.java:750)

```
We have the appropriate permissions to the folder it’s trying to write to.

I see an issue was raised and fixed (https://issues.apache.org/jira/browse/IGNITE-3239) back in 2016 so I wonder if it’s a regression related to that?

Thanks.

**Comment by ptupitsyn** [comment]
Do those multiple applications use the same Ignite work directory?

**Comment by JamesPDev** [comment]
Each project has a package reference for Ignite but the IGNITE_HOME environment variable specifying where to find Ignite is the same for all apps. Is that an invalid setup?

**Comment by ptupitsyn** [comment]
1. If you have a package reference, you don't need a separate binary distribution (`apache-ignite-slim-2.15.0-bin`).
2. Yes, every Ignite node (in your case - app) should have it's own work directory. That is achieved naturally with a package reference and without an explicit `IGNITE_HOME`.

**Comment by JamesPDev** [comment]
The reason for having a separate installation rather than just relying on the nuget package reference is mainly historic as we originally ran into issues with jar files not being copied (fixed in https://github.com/apache/ignite/pull/6954 I believe). We also needed to access the REST API. Can you confirm the REST API is accessible when using the nuget packages?

**Comment by ptupitsyn** [comment]
> Can you confirm the REST API is accessible when using the nuget packages?

Kind of. You'll have to get `ignite-rest-http` module separately (from Maven or from the binary distribution), put it somewhere, and provide the path to it in `IgniteConfiguration.JvmClasspath`.

> why the error we see has only started to occur with the new version of Ignite

It may be a coincidence. The error is caused by multiple instances of Ignite trying to access the same file at the same time.

**Comment by JamesPDev** [comment]
Ok, one last thing, are there any plans to progress https://issues.apache.org/jira/plugins/servlet/mobile#issue/IGNITE-3275 as we still have the webconsole running. Thanks.

**Comment by ptupitsyn** [comment]
Unfortunately, there are no plans for that ticket.
