### ISSUE TITLE
Thin client stopped connecting to Ignite cluster from version 2.15

### ISSUE THREAD

**Issue by chronomanta** [apache/ignite#11268]
## Environment:
- Ignite cluster running on Docker (for simplicity only one node, but the effect is completely the same for bigger clusters)
- Thin client in local network

### Cluster:
```
docker run -d -p 10800:10800 -p 8080:8080 -e "OPTION_LIBS=ignite-rest-http" apacheignite/ignite:2.16.0
```

### Client:
```
public class App
{
    public static void main( String[] args )
    {
        System.out.println("Starting Ignite thin client");
        ClientConfiguration cfg = new ClientConfiguration()
                .setAddresses("192.168.1.16:10800")
                .setTimeout(5000);
        try (IgniteClient client = Ignition.startClient(cfg)) {
            System.out.println("Getting the cache");
            final ClientCache<String, String> someCache = client.getOrCreateCache("some_cache");
            System.out.println("Elements in cache: " + someCache.size());
        }
        System.out.println("Exiting");
    }
}
```

**Result with 2.14.0:**
pom.xml
```
<dependency>
    <groupId>org.apache.ignite</groupId>
    <artifactId>ignite-core</artifactId>
    <version>2.14.0</version>
</dependency>
```

```
Starting Ignite thin client
Getting the cache
Elements in cache: 0
Exiting

Process finished with exit code 0
```

**Result with 2.16.0:**
pom.xml
```
<dependency>
    <groupId>org.apache.ignite</groupId>
    <artifactId>ignite-core</artifactId>
    <version>2.16.0</version>
</dependency>
```

```
Starting Ignite thin client
Exception in thread "main" org.apache.ignite.client.ClientConnectionException: Connect timed out
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:197)
	at org.apache.ignite.internal.client.thin.TcpClientChannel.<init>(TcpClientChannel.java:208)
	at org.apache.ignite.internal.client.thin.ReliableChannel$ClientChannelHolder.getOrCreateChannel(ReliableChannel.java:1038)
	at org.apache.ignite.internal.client.thin.ReliableChannel$ClientChannelHolder.getOrCreateChannel(ReliableChannel.java:1016)
	at org.apache.ignite.internal.client.thin.ReliableChannel$ClientChannelHolder.access$300(ReliableChannel.java:965)
	at org.apache.ignite.internal.client.thin.ReliableChannel.applyOnDefaultChannel(ReliableChannel.java:832)
	at org.apache.ignite.internal.client.thin.ReliableChannel.applyOnDefaultChannel(ReliableChannel.java:788)
	at org.apache.ignite.internal.client.thin.TcpIgniteClient.retrieveBinaryConfiguration(TcpIgniteClient.java:474)
	at org.apache.ignite.internal.client.thin.TcpIgniteClient.<init>(TcpIgniteClient.java:146)
	at org.apache.ignite.internal.client.thin.TcpIgniteClient.<init>(TcpIgniteClient.java:118)
	at org.apache.ignite.internal.client.thin.TcpIgniteClient.start(TcpIgniteClient.java:426)
	at org.apache.ignite.Ignition.startClient(Ignition.java:587)
	at org.example.App.main(App.java:20)
	Suppressed: org.apache.ignite.client.ClientConnectionException
		... 13 more
	Caused by: org.apache.ignite.client.ClientConnectionException
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
		... 12 more
	Caused by: java.net.UnknownHostException
		at java.base/sun.nio.ch.Net.translateException(Net.java:215)
		at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:107)
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
		... 12 more
	Suppressed: org.apache.ignite.client.ClientConnectionException: Connection refused
		... 13 more
		Suppressed: org.apache.ignite.client.ClientConnectionException: Connect timed out
			... 13 more
		Caused by: org.apache.ignite.client.ClientConnectionException: Connect timed out
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
			... 12 more
		Caused by: java.net.SocketTimeoutException: Connect timed out
			at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1195)
			at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1233)
			at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
			... 12 more
		Suppressed: org.apache.ignite.client.ClientConnectionException
			... 13 more
		Caused by: org.apache.ignite.client.ClientConnectionException
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
			... 12 more
		Caused by: java.net.UnknownHostException
			at java.base/sun.nio.ch.Net.translateException(Net.java:215)
			at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:107)
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
			... 12 more
	Caused by: org.apache.ignite.client.ClientConnectionException: Connection refused
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
		... 12 more
	Caused by: java.net.ConnectException: Connection refused
		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
		at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
		at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1191)
		at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1233)
		at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
		... 12 more
	Suppressed: org.apache.ignite.client.ClientConnectionException: Connect timed out
		... 13 more
		Suppressed: org.apache.ignite.client.ClientConnectionException
			... 13 more
		Caused by: org.apache.ignite.client.ClientConnectionException
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
			... 12 more
		Caused by: java.net.UnknownHostException
			at java.base/sun.nio.ch.Net.translateException(Net.java:215)
			at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:107)
			at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
			... 12 more
	Caused by: org.apache.ignite.client.ClientConnectionException: Connect timed out
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
		... 12 more
	Caused by: java.net.SocketTimeoutException: Connect timed out
		at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1195)
		at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1233)
		at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
		at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
		... 12 more
Caused by: org.apache.ignite.client.ClientConnectionException: Connect timed out
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:172)
	... 12 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.SocketChannelImpl.finishTimedConnect(SocketChannelImpl.java:1195)
	at java.base/sun.nio.ch.SocketChannelImpl.blockingConnect(SocketChannelImpl.java:1233)
	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:102)
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnectionMultiplexer.open(GridNioClientConnectionMultiplexer.java:152)
	... 12 more

Process finished with exit code 1
```

For version 2.15.0 the result is identical. 
Were there any breaking changes between 2.14 and 2.15 that could be the reason of that?

**Comment by ptupitsyn** [comment]
There were no breaking changes, client 2.14 should work with server 2.15 and 2.16.

Looks like a networking/configuration issue to me - the client does not reach the server. If there was a protocol breakdown/incompatibility, we would see a different error.

**Comment by chronomanta** [comment]
Client 2.14 connects to server in version 2.14,15,16 without any problems.
Clients 2.15 and 2.16 is unable to connect to server in any version. Configuration is the same (no custom configuration, just server address:port - 192.168.1.16:10800) and the code is the same - I'm changing the client version in maven only (even just one digit from 4 to higher) and it stops working.
