### ISSUE TITLE
Ignite 2.16 is incompatible with recent h2database

### ISSUE THREAD

**Issue by magicprinc** [apache/ignite#11333]
com.h2database:h2:2.2.224

```
java.lang.NoClassDefFoundError: org/h2/value/ValueByte

	at org.apache.ignite.internal.processors.query.h2.twostep.msg.GridH2ValueMessageFactory.registerAll(GridH2ValueMessageFactory.java:40)
	at org.apache.ignite.internal.managers.communication.IgniteMessageFactoryImpl.<init>(IgniteMessageFactoryImpl.java:72)
	at org.apache.ignite.internal.managers.communication.GridIoManager.start(GridIoManager.java:482)
	at org.apache.ignite.internal.IgniteKernal.startManager(IgniteKernal.java:1774)
	at org.apache.ignite.internal.IgniteKernal.start(IgniteKernal.java:1008)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start0(IgnitionEx.java:1725)
	at org.apache.ignite.internal.IgnitionEx$IgniteNamedInstance.start(IgnitionEx.java:1647)
	at org.apache.ignite.internal.IgnitionEx.start0(IgnitionEx.java:1089)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:625)
	at org.apache.ignite.internal.IgnitionEx.start(IgnitionEx.java:547)
	at org.apache.ignite.Ignition.start(Ignition.java:300)
	at ignite.ExpireTest.expireListener(ExpireTest.java:32)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: org.h2.value.ValueByte
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 15 more

```

**Comment by magicprinc** [comment]
@nao-it No, I have another problem. I use some library, which depends on new h2. And new h2 conflict with ignite.h2. The good solution is shading. GridGain Community has shaded h2 ⇒ no public dependency, all classes bundled with different package name.

More theory on the topic "shading"
https://imperceptiblethoughts.com/shadow/
