### ISSUE TITLE
lz4 upgrade

### ISSUE THREAD

**Issue by guoliangxue01** [apache/ignite#11378]
Hi Ignite Team,

[org.lz4](https://mvnrepository.com/artifact/net.jpountz.lz4/lz4) has been moved to [lz4-java](https://mvnrepository.com/artifact/org.lz4/lz4-java).
If I use ignite-compress (2.16.0) where org.lz4 has been removed, but the latest class CompressionProcessorImpl
in the ignite is still using org.lz4 to compress, which leads to

_Caused by: java.lang.NoClassDefFoundError: net/jpountz/lz4/LZ4Factory
igniteserver-1  | 	at org.apache.ignite.internal.processors.compress.CompressionProcessorImpl$Lz4.<clinit>(CompressionProcessorImpl.java:429)
igniteserver-1  | 	at org.apache.ignite.internal.processors.compress.CompressionProcessorImpl.maxCompressedBufferSize(CompressionProcessorImpl.java:419)
igniteserver-1  | 	at org.apache.ignite.internal.processors.compress.CompressionProcessorImpl.<init>(CompressionProcessorImpl.java:56)_

do you have any plan to upgrade it to lz4-java as well?

**Comment by ptupitsyn** [comment]
* `ignite-compress` 2.16 depends on `lz4-java`: https://central.sonatype.com/artifact/org.apache.ignite/ignite-compress/dependencies
* `net.jpountz.lz4.LZ4Factory` is part of `lz4-java`: https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/lz4/LZ4Factory.java

It works as expected, please make sure you have `lz4-java` in classpath.
