### ISSUE TITLE
java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by msput86** [apache/ignite#11772]
Sometimes we catch the exception java.nio.BufferUnderflowException.
```
java.nio.BufferUnderflowException: null
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:707)
	at java.base/java.nio.HeapByteBuffer.getInt(HeapByteBuffer.java:435)
	at org.apache.ignite.internal.binary.streams.BinaryByteBufferInputStream.readInt(BinaryByteBufferInputStream.java:111)
	at org.apache.ignite.internal.binary.BinaryReaderExImpl.readInt(BinaryReaderExImpl.java:746)
	at org.apache.ignite.internal.client.thin.ClientCacheAffinityMapping.readCacheKeyConfiguration(ClientCacheAffinityMapping.java:240)
	at org.apache.ignite.internal.client.thin.ClientCacheAffinityMapping.readResponse(ClientCacheAffinityMapping.java:197)
	at org.apache.ignite.internal.client.thin.ClientCacheAffinityContext.readPartitionsUpdateResponse(ClientCacheAffinityContext.java:154)
	at org.apache.ignite.internal.client.thin.TcpClientChannel.receive(TcpClientChannel.java:412)
	at org.apache.ignite.internal.client.thin.TcpClientChannel.service(TcpClientChannel.java:311)
	at org.apache.ignite.internal.client.thin.ReliableChannel.lambda$affinityInfoIsUpToDate$6(ReliableChannel.java:423)
	at org.apache.ignite.internal.client.thin.ReliableChannel.applyOnNodeChannel(ReliableChannel.java:746)
	at org.apache.ignite.internal.client.thin.ReliableChannel.affinityInfoIsUpToDate(ReliableChannel.java:422)
	at org.apache.ignite.internal.client.thin.ReliableChannel.affinityService(ReliableChannel.java:316)
	at org.apache.ignite.internal.client.thin.TcpClientCache.txAwareService(TcpClientCache.java:1132)
	at org.apache.ignite.internal.client.thin.TcpClientCache.cacheSingleKeyOperation(TcpClientCache.java:1191)
	at org.apache.ignite.internal.client.thin.TcpClientCache.get(TcpClientCache.java:146)
My thin client config:
 ClientConfiguration conf = new ClientConfiguration();
            conf.setAddresses(...);
            conf.setHeartbeatEnabled(true);
            conf.setHeartbeatInterval(30000);
            conf.setPartitionAwarenessEnabled(true);
            conf.setTimeout(7000);
            conf.setReconnectThrottlingPeriod(10000);
  There is  my 2 caches  (but server runs more than 30 other caches)        
      new ClientCacheConfiguration()
                    .setName(config.getProviderCacheName())
                    .setCacheMode(CacheMode.PARTITIONED)
                    .setQueryEntities(new QueryEntity(String.class, Provider.class))
                    .setCopyOnRead(false)
                    .setDataRegionName("prv_region")
                    .setBackups(1)
                    .setGroupName("prv_group")
                    .setStatisticsEnabled(true);   
    new ClientCacheConfiguration()
                    .setName(config.getProviderIdxCacheName())
                    .setCacheMode(CacheMode.PARTITIONED)
                    .setQueryEntities(new QueryEntity(Long.class, IdProvider.class))
                    .setDataRegionName("prv_region")
                    .setBackups(1)
                    .setOnheapCacheEnabled(true)
                    .setGroupName("prv_group")
                    .setStatisticsEnabled(true);
```    
  How we can avoid this exception?        
  Ignite 2.15.0 (client and server)

**Comment by ptupitsyn** [comment]
Please add:
* Client version
* Server version

**Comment by msput86** [comment]
This happens when someone creates a cache in the neighboring data region(and group).

**Comment by msput86** [comment]
https://issues.apache.org/jira/browse/IGNITE-20038 - fixed
